Implementation of the Transaction status API
collinsmuriuki/mpesa-rust pull request #55
Opened 2022-11-22 19:19 UTC by itsyaasir

2022-11-24 21:01 UTC, collinsmuriuki requested changes

2022-11-24 21:03 UTC, collinsmuriuki commented
> I have just realized through out the services API , we have a typo in the Response struct and I just noticed it now. Take a look at the `OriginatorCoversationID`.
> 
> ```rust
>     #[serde(rename(deserialize = "OriginatorCoversationID"))]
>     pub originator_coversation_id: String,
> ```
> 
> Does safaricom API returns something like this ?

The API returns `OriginatorCoversationID`. If the value was incorrect, then deserialization would fail

2022-11-24 21:04 UTC, collinsmuriuki commented
Good work 👍🏽

2022-11-25 02:34 UTC, itsyaasir commented on Cargo.toml
> -transaction_reversal = ["dep:openssl", "dep:base64"]
It was a mistake, I'll return them again.

2022-11-25 04:14 UTC, itsyaasir commented on Cargo.toml
> -transaction_reversal = ["dep:openssl", "dep:base64"]
Done

2022-11-25 05:04 UTC, itsyaasir commented
It's like this test behaves sporadically `stk_push_test::stk_push_test`

2022-11-25 05:06 UTC, collinsmuriuki commented
Yes very annoying, the API on sandbox will randomly return an error response. Will address this soon though

2022-11-25 05:07 UTC, itsyaasir commented
> Yes very annoying, the API on sandbox will randomly return an error response. Will address this soon though

You can approve this so we can merge it in and close the issue.

2022-11-25 05:07 UTC, collinsmuriuki approved these changes

2022-11-25 05:07 UTC, merged